region       = "us-east-1"
profile      = "fvelasco"
project_name = "id-sbdx-felipe-velasco"
ambiente     = "Investigación y Desarrollo"
owner        = "Felipe Velasco"
ownerEmail   = "felipe.velasco@baaskit.com"
